
import BatmanLogo from '../assets/Logos/Batman.png';
import GoogleLogo from '../assets/Logos/flat-color-icons_google.svg';
import TeslaLogo from '../assets/Logos/Tesla.png';
const jobs = [
    {
      id: 1,
      logo: TeslaLogo,
      title: 'Deep learning Engineer',
      location: 'Sydney, Australia',
      expiration: 25,
      tags: ['Remote', 'Entry Level', 'Full Time'],
      salary: '50K - 80K AUD(Yearly)',
      company: 'Tesla Inc.',
      saved: true,
    },
    {
      id: 2,
      logo: BatmanLogo,
      title: 'Game Developer',
      location: 'Melbourn, Australia',
      expiration: 25,
      tags: ['Onsite', 'Intermediate', 'Internship'],
      salary: '50K - 90K AUD(Yearly)',
      company: 'The Batman Corporation',
      saved: false,
    },
    {
      id: 3,
      logo: GoogleLogo,
      title: 'AI Engineer',
      location: 'Perth, Australia',
      expiration: 25,
      tags: ['Hybrid', 'Experienced', 'Full Time'],
      salary: '20K - 50K AUD(Yearly)',
      company: 'Google',
      saved: true,
    },
    {
      id: 4,
      logo: BatmanLogo,
      title: 'Software Engineer',
      location: 'Melbourn, Australia',
      expiration: 25,
      tags: ['Onsite', 'Intermediate', 'Internship'],
      salary: '50K - 90K AUD(Yearly)',
      company: 'The Batman Corporation',
      saved: true,
    },
    {
      id: 5,
      logo: GoogleLogo,
      title: 'Data Scientist',
      location: 'Perth, Australia',
      expiration: 25,
      tags: ['Hybrid', 'Experienced', 'Full Time'],
      salary: '20K - 50K AUD(Yearly)',
      company: 'Google',
      saved: false,
    },
    {
      id: 6,
      logo: TeslaLogo,
      title: 'Product Designer',
      location: 'Sydney, Australia',
      expiration: 25,
      tags: ['Remote', 'Entry Level', 'Full Time'],
      salary: '50K - 80K AUD(Yearly)',
      company: 'Tesla Inc.',
      saved: true,
    },
    {
      id: 7,
      logo: TeslaLogo,
      title: 'Deep learning Engineer',
      location: 'Sydney, Australia',
      expiration: 25,
      tags: ['Remote', 'Entry Level', 'Full Time'],
      salary: '50K - 80K AUD(Yearly)',
      company: 'Tesla Inc.',
      saved: true,
    },
    {
      id: 8,
      logo: BatmanLogo,
      title: 'Game Developer',
      location: 'Melbourn, Australia',
      expiration: 25,
      tags: ['Onsite', 'Intermediate', 'Internship'],
      salary: '50K - 90K AUD(Yearly)',
      company: 'The Batman Corporation',
      saved: false,
    },
    {
      id: 9,
      logo: GoogleLogo,
      title: 'AI Engineer',
      location: 'Perth, Australia',
      expiration: 25,
      tags: ['Hybrid', 'Experienced', 'Full Time'],
      salary: '20K - 50K AUD(Yearly)',
      company: 'Google',
      saved: true,
    },
    {
      id: 10,
      logo: BatmanLogo,
      title: 'Software Engineer',
      location: 'Melbourn, Australia',
      expiration: 25,
      tags: ['Onsite', 'Intermediate', 'Internship'],
      salary: '50K - 90K AUD(Yearly)',
      company: 'The Batman Corporation',
      saved: true,
    },
    {
      id: 11,
      logo: GoogleLogo,
      title: 'Data Scientist',
      location: 'Perth, Australia',
      expiration: 25,
      tags: ['Hybrid', 'Experienced', 'Full Time'],
      salary: '20K - 50K AUD(Yearly)',
      company: 'Google',
      saved: false,
    },
    {
      id: 12,
      logo: TeslaLogo,
      title: 'Product Designer',
      location: 'Sydney, Australia',
      expiration: 25,
      tags: ['Remote', 'Entry Level', 'Full Time'],
      salary: '50K - 80K AUD(Yearly)',
      company: 'Tesla Inc.',
      saved: true,
    },
  ];

  export default jobs